#!/bin/bash
cd hugo && (
	[ ! -e hugo_0.81.0_Linux-64bit.tar.gz ] && \
		wget https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_0.81.0_Linux-64bit.tar.gz
	tar -xzf hugo_0.81.0_Linux-64bit.tar.gz
)
